sudo: false

language: php
php:
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer install

script:
  - composer validate
  - ./vendor/bin/phpunit
